num=int(input("enter your number upto 5 digits: "))
if num>=0 and num<=9: print("single digit number")
elif num>=10 and num<=99: print("two digit number")
elif num>=100 and num<=999: print("three digit number")
elif num>=1000 and num<=9999: print("four digit number")
else: print("five digit number")